In [1]:
# Numpy
Data -> vectors(arrays) of numbers
Computer understands Binary ->

1

In [ ]:
# Scalar - 12

# vector - 1D array - a -> [0.1, 0.2, 0.3,0.4] * 5

# matrix -> 2D Array - row, columns

# Tensors -> multi 2d array

In [3]:
lst = [10, 20, 30, 40]
[ele*2 for ele in lst]

[20, 40, 60, 80]

In [2]:
import array
my_arr = array.array('i', [1, 2, 3, 4, 5])
print(my_arr, type(my_arr))
print(my_arr*2)

array('i', [1, 2, 3, 4, 5]) <class 'array.array'>
array('i', [1, 2, 3, 4, 5, 1, 2, 3, 4, 5])


In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
arr1*2

array([ 2,  4,  6,  8, 10])

In [ ]:
# 1. Lists are highly flexible. -
# 2. Arrays provide better performance - Collection of homogeneous data

# List - Heterogeneous, Array - homogeneous
# List - Less Effiecient, Arrays - Efficient
# List - Slow in mathematical operations, Arrays - faster in mathematical operations(vectorized)

In [ ]:
# Limitation of the array is - it works with one dimensional array only
# Numpy allows you to work with multidimensional array

# Pandas, Scikitlearn, Matplotlib, seaborn, tensorflow - Numpy

In [5]:
import numpy as np

In [17]:
# Creating an array out of list from homogeneous elements
arr = np.array([10, 20, 30, 40, 50])
print(arr, type(arr))

# ndarray - Multidimensional array

[10 20 30 40 50] <class 'numpy.ndarray'>


In [7]:
# Array is a collection of homogeneous elements
print(arr.dtype)       # # What kind of data you have inside the array

int64


In [10]:
arr1 = np.array([10.0, '20', 30, 40, 50])
print(arr1, type(arr1))

['10.0' '20' '30' '40' '50'] <class 'numpy.ndarray'>


In [12]:
# Type of elements of the array
print(arr1.dtype)

<U32


In [13]:
arr1.shape

(5,)

In [14]:
# Size of an array - total no of elements inside the array
print(arr1.size)

5


In [15]:
# Dimension of the array    - Gives te number of dimension of the array
print(arr1.ndim)

1


In [18]:
# Number of bytes taken by array to store all elements in the array
arr.nbytes

40

In [ ]:
# Upcasting
# Object
# String
# Complex
# Float
# int

In [19]:
# Creating an array with heterogeneous elements
arr2 = np.array([10,20,30,40,50, 60.70, 80+90j])
print(arr2)
print(arr2.dtype)

[10.  +0.j 20.  +0.j 30.  +0.j 40.  +0.j 50.  +0.j 60.7 +0.j 80. +90.j]
complex128


In [20]:
# Creating an array with heterogeneous elements
arr3 = np.array((10,20,30,40,50, 60.70, 80+90j, '100'))
print(arr3)
print(arr3.dtype)

['10' '20' '30' '40' '50' '60.7' '(80+90j)' '100']
<U64


In [21]:
# Creating an array with heterogeneous elements
arr4 = np.array([10,20,30,40,50, 60.70, 80+90j, '100', [110, 20]], dtype = object)
print(arr4)
print(arr4.dtype)

# VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences
#  (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes)
#  is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.

[10 20 30 40 50 60.7 (80+90j) '100' list([110, 20])]
object


In [22]:
# Creating 2D array
arr5 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# Functions to create an array

# arange(start, stop, step)

# Arange can take a fractional value as step whereas range can take only integer value

arr1 = np.arange(10, 21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [24]:
arr1 = np.arange(10, 21, 0.5)
print(arr1)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5]


In [29]:
# I want to generate an array of 100 numbers in the same range?
# linspace(start, stop, no_of_elements)
# Stop is inclusive
arr2 = np.linspace(10, 21, 100)
arr2

array([10.        , 10.11111111, 10.22222222, 10.33333333, 10.44444444,
       10.55555556, 10.66666667, 10.77777778, 10.88888889, 11.        ,
       11.11111111, 11.22222222, 11.33333333, 11.44444444, 11.55555556,
       11.66666667, 11.77777778, 11.88888889, 12.        , 12.11111111,
       12.22222222, 12.33333333, 12.44444444, 12.55555556, 12.66666667,
       12.77777778, 12.88888889, 13.        , 13.11111111, 13.22222222,
       13.33333333, 13.44444444, 13.55555556, 13.66666667, 13.77777778,
       13.88888889, 14.        , 14.11111111, 14.22222222, 14.33333333,
       14.44444444, 14.55555556, 14.66666667, 14.77777778, 14.88888889,
       15.        , 15.11111111, 15.22222222, 15.33333333, 15.44444444,
       15.55555556, 15.66666667, 15.77777778, 15.88888889, 16.        ,
       16.11111111, 16.22222222, 16.33333333, 16.44444444, 16.55555556,
       16.66666667, 16.77777778, 16.88888889, 17.        , 17.11111111,
       17.22222222, 17.33333333, 17.44444444, 17.55555556, 17.66

In [30]:
arr2.itemsize     # no of bytes taken by each element in the array.

8

In [28]:
arr2.dtype

dtype('float64')

### Changing the shape of an array

In [31]:
# Random.randint(val1, val2, no_of_ele)
# Creating an array by specified no_of_ele and values will be selected randomly between val1 and val2

arr1 = np.random.randint(10, 70, 70)
arr1

array([42, 17, 56, 13, 18, 53, 34, 36, 20, 60, 68, 51, 50, 17, 34, 52, 44,
       52, 68, 53, 49, 33, 26, 25, 48, 50, 40, 40, 39, 34, 10, 61, 46, 29,
       35, 32, 30, 23, 60, 29, 22, 43, 56, 34, 53, 22, 39, 47, 31, 19, 45,
       45, 25, 68, 18, 55, 45, 54, 57, 28, 38, 20, 62, 21, 12, 67, 20, 59,
       47, 37])

In [32]:
arr1.shape

(70,)

While reshaping the array, no of elements in the original array and multiplication of dimension on reshaping should be equal, otherwise it will give ValueError

In [34]:
# Reshape function does not make any changes to existing array
arr2 = arr1.reshape(10, 7)
arr2

array([[42, 17, 56, 13, 18, 53, 34],
       [36, 20, 60, 68, 51, 50, 17],
       [34, 52, 44, 52, 68, 53, 49],
       [33, 26, 25, 48, 50, 40, 40],
       [39, 34, 10, 61, 46, 29, 35],
       [32, 30, 23, 60, 29, 22, 43],
       [56, 34, 53, 22, 39, 47, 31],
       [19, 45, 45, 25, 68, 18, 55],
       [45, 54, 57, 28, 38, 20, 62],
       [21, 12, 67, 20, 59, 47, 37]])

In [35]:
arr1

array([42, 17, 56, 13, 18, 53, 34, 36, 20, 60, 68, 51, 50, 17, 34, 52, 44,
       52, 68, 53, 49, 33, 26, 25, 48, 50, 40, 40, 39, 34, 10, 61, 46, 29,
       35, 32, 30, 23, 60, 29, 22, 43, 56, 34, 53, 22, 39, 47, 31, 19, 45,
       45, 25, 68, 18, 55, 45, 54, 57, 28, 38, 20, 62, 21, 12, 67, 20, 59,
       47, 37])

In [36]:
arr3 = np.random.randint(10, 70, 71)
arr3

array([65, 32, 16, 17, 40, 33, 20, 42, 31, 60, 45, 33, 10, 59, 22, 39, 25,
       61, 64, 48, 28, 11, 12, 30, 60, 41, 66, 46, 43, 27, 23, 69, 22, 32,
       43, 36, 32, 41, 33, 65, 26, 59, 21, 32, 24, 18, 43, 23, 55, 41, 60,
       17, 23, 55, 12, 43, 53, 56, 19, 51, 33, 22, 65, 56, 56, 23, 49, 15,
       19, 45, 49])

In [37]:
# arr3.reshape(10, 7)
# arr3

In [40]:
arr3

array([65, 32, 16, 17, 40, 33, 20, 42, 31, 60, 45, 33, 10, 59, 22, 39, 25,
       61, 64, 48, 28, 11, 12, 30, 60, 41, 66, 46, 43, 27, 23, 69, 22, 32,
       43, 36, 32, 41, 33, 65, 26, 59, 21, 32, 24, 18, 43, 23, 55, 41, 60,
       17, 23, 55, 12, 43, 53, 56, 19, 51, 33, 22, 65, 56, 56, 23, 49, 15,
       19, 45, 49])

In [38]:
arr3.reshape(1, 71)

array([[65, 32, 16, 17, 40, 33, 20, 42, 31, 60, 45, 33, 10, 59, 22, 39,
        25, 61, 64, 48, 28, 11, 12, 30, 60, 41, 66, 46, 43, 27, 23, 69,
        22, 32, 43, 36, 32, 41, 33, 65, 26, 59, 21, 32, 24, 18, 43, 23,
        55, 41, 60, 17, 23, 55, 12, 43, 53, 56, 19, 51, 33, 22, 65, 56,
        56, 23, 49, 15, 19, 45, 49]])

In [39]:
arr3.reshape(71, 1)

array([[65],
       [32],
       [16],
       [17],
       [40],
       [33],
       [20],
       [42],
       [31],
       [60],
       [45],
       [33],
       [10],
       [59],
       [22],
       [39],
       [25],
       [61],
       [64],
       [48],
       [28],
       [11],
       [12],
       [30],
       [60],
       [41],
       [66],
       [46],
       [43],
       [27],
       [23],
       [69],
       [22],
       [32],
       [43],
       [36],
       [32],
       [41],
       [33],
       [65],
       [26],
       [59],
       [21],
       [32],
       [24],
       [18],
       [43],
       [23],
       [55],
       [41],
       [60],
       [17],
       [23],
       [55],
       [12],
       [43],
       [53],
       [56],
       [19],
       [51],
       [33],
       [22],
       [65],
       [56],
       [56],
       [23],
       [49],
       [15],
       [19],
       [45],
       [49]])

In [ ]:
# 2D shape -> (row, col)
# 3D Shape -> (height, row, col)

In [41]:
arr1 = np.random.randint(10, 50, 100)
arr1

array([33, 13, 25, 29, 38, 19, 19, 20, 31, 10, 45, 27, 29, 24, 12, 42, 25,
       19, 44, 29, 48, 13, 14, 15, 48, 43, 32, 33, 41, 36, 33, 16, 14, 32,
       32, 41, 34, 21, 20, 48, 24, 31, 17, 48, 29, 47, 48, 27, 16, 13, 24,
       34, 41, 30, 44, 17, 17, 46, 30, 42, 10, 27, 15, 48, 28, 23, 34, 20,
       10, 48, 11, 46, 12, 35, 39, 31, 44, 37, 24, 17, 29, 16, 39, 16, 38,
       35, 25, 32, 10, 14, 22, 40, 33, 28, 28, 10, 17, 13, 42, 45])

In [42]:
arr2 = arr1
arr2

array([33, 13, 25, 29, 38, 19, 19, 20, 31, 10, 45, 27, 29, 24, 12, 42, 25,
       19, 44, 29, 48, 13, 14, 15, 48, 43, 32, 33, 41, 36, 33, 16, 14, 32,
       32, 41, 34, 21, 20, 48, 24, 31, 17, 48, 29, 47, 48, 27, 16, 13, 24,
       34, 41, 30, 44, 17, 17, 46, 30, 42, 10, 27, 15, 48, 28, 23, 34, 20,
       10, 48, 11, 46, 12, 35, 39, 31, 44, 37, 24, 17, 29, 16, 39, 16, 38,
       35, 25, 32, 10, 14, 22, 40, 33, 28, 28, 10, 17, 13, 42, 45])

In [43]:
arr2.shape = (2, 5, 10)
arr2

array([[[33, 13, 25, 29, 38, 19, 19, 20, 31, 10],
        [45, 27, 29, 24, 12, 42, 25, 19, 44, 29],
        [48, 13, 14, 15, 48, 43, 32, 33, 41, 36],
        [33, 16, 14, 32, 32, 41, 34, 21, 20, 48],
        [24, 31, 17, 48, 29, 47, 48, 27, 16, 13]],

       [[24, 34, 41, 30, 44, 17, 17, 46, 30, 42],
        [10, 27, 15, 48, 28, 23, 34, 20, 10, 48],
        [11, 46, 12, 35, 39, 31, 44, 37, 24, 17],
        [29, 16, 39, 16, 38, 35, 25, 32, 10, 14],
        [22, 40, 33, 28, 28, 10, 17, 13, 42, 45]]])

In [44]:
arr1

array([[[33, 13, 25, 29, 38, 19, 19, 20, 31, 10],
        [45, 27, 29, 24, 12, 42, 25, 19, 44, 29],
        [48, 13, 14, 15, 48, 43, 32, 33, 41, 36],
        [33, 16, 14, 32, 32, 41, 34, 21, 20, 48],
        [24, 31, 17, 48, 29, 47, 48, 27, 16, 13]],

       [[24, 34, 41, 30, 44, 17, 17, 46, 30, 42],
        [10, 27, 15, 48, 28, 23, 34, 20, 10, 48],
        [11, 46, 12, 35, 39, 31, 44, 37, 24, 17],
        [29, 16, 39, 16, 38, 35, 25, 32, 10, 14],
        [22, 40, 33, 28, 28, 10, 17, 13, 42, 45]]])

In [45]:
# Flattening of the array - Converting higher dimension array into single dinemnsion - ravel()
arr1

array([[[33, 13, 25, 29, 38, 19, 19, 20, 31, 10],
        [45, 27, 29, 24, 12, 42, 25, 19, 44, 29],
        [48, 13, 14, 15, 48, 43, 32, 33, 41, 36],
        [33, 16, 14, 32, 32, 41, 34, 21, 20, 48],
        [24, 31, 17, 48, 29, 47, 48, 27, 16, 13]],

       [[24, 34, 41, 30, 44, 17, 17, 46, 30, 42],
        [10, 27, 15, 48, 28, 23, 34, 20, 10, 48],
        [11, 46, 12, 35, 39, 31, 44, 37, 24, 17],
        [29, 16, 39, 16, 38, 35, 25, 32, 10, 14],
        [22, 40, 33, 28, 28, 10, 17, 13, 42, 45]]])

In [46]:
arr1.ravel()

array([33, 13, 25, 29, 38, 19, 19, 20, 31, 10, 45, 27, 29, 24, 12, 42, 25,
       19, 44, 29, 48, 13, 14, 15, 48, 43, 32, 33, 41, 36, 33, 16, 14, 32,
       32, 41, 34, 21, 20, 48, 24, 31, 17, 48, 29, 47, 48, 27, 16, 13, 24,
       34, 41, 30, 44, 17, 17, 46, 30, 42, 10, 27, 15, 48, 28, 23, 34, 20,
       10, 48, 11, 46, 12, 35, 39, 31, 44, 37, 24, 17, 29, 16, 39, 16, 38,
       35, 25, 32, 10, 14, 22, 40, 33, 28, 28, 10, 17, 13, 42, 45])

In [47]:
# Transpose of an array - rows to columns and vice versa
arr2.shape = (10, 10)
arr2

array([[33, 13, 25, 29, 38, 19, 19, 20, 31, 10],
       [45, 27, 29, 24, 12, 42, 25, 19, 44, 29],
       [48, 13, 14, 15, 48, 43, 32, 33, 41, 36],
       [33, 16, 14, 32, 32, 41, 34, 21, 20, 48],
       [24, 31, 17, 48, 29, 47, 48, 27, 16, 13],
       [24, 34, 41, 30, 44, 17, 17, 46, 30, 42],
       [10, 27, 15, 48, 28, 23, 34, 20, 10, 48],
       [11, 46, 12, 35, 39, 31, 44, 37, 24, 17],
       [29, 16, 39, 16, 38, 35, 25, 32, 10, 14],
       [22, 40, 33, 28, 28, 10, 17, 13, 42, 45]])

In [48]:
arr2.T

array([[33, 45, 48, 33, 24, 24, 10, 11, 29, 22],
       [13, 27, 13, 16, 31, 34, 27, 46, 16, 40],
       [25, 29, 14, 14, 17, 41, 15, 12, 39, 33],
       [29, 24, 15, 32, 48, 30, 48, 35, 16, 28],
       [38, 12, 48, 32, 29, 44, 28, 39, 38, 28],
       [19, 42, 43, 41, 47, 17, 23, 31, 35, 10],
       [19, 25, 32, 34, 48, 17, 34, 44, 25, 17],
       [20, 19, 33, 21, 27, 46, 20, 37, 32, 13],
       [31, 44, 41, 20, 16, 30, 10, 24, 10, 42],
       [10, 29, 36, 48, 13, 42, 48, 17, 14, 45]])

Arithmetic Operation on array


In [ ]:
# Arithmetic Operators on array perfomrs the operation elementwise
arr1 = np.random.randint(10, 20, 10)
print(arr1)


# Mathematical Operations

print(arr1+5)
print(arr1-5)
print(arr1*5)
print(arr1/5)
print(arr1//5)
print(arr1%5)
print(arr1**5)

In [53]:
# Comparison operations
print(arr1>5)
print(arr1<5)
print(arr1<=5)
print(arr1>=5)
print(arr1==5)
print(arr1!=5)
print(arr1&5)

[ True  True  True  True  True]
[False False False False False]
[False False False False False]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[0 5 0 4 0]


In [55]:
# To perform these operation on the array, the dimension and shape of the array should remain same

arr1 = np.random.randint(10, 90, 5)
arr2 = np.random.randint(10, 90, 5)
print(arr1)
print(arr2)

[85 31 26 21 51]
[11 89 76 38 24]


In [52]:
# Arithmetic operations - element wise
print(arr2+arr1)
print(arr2-arr1)
print(arr2*arr1)
print(arr2/arr1)
print(arr2//arr1)
print(arr2%arr1)
print(arr2**arr1)

[112  93  99 135 114]
[60 19 63 43 46]
[2236 2072 1458 4094 2720]
[3.30769231 1.51351351 4.5        1.93478261 2.35294118]
[3 1 4 1 2]
[ 8 19  9 43 12]
[  825091346980143104                    0  2190886001003067041
 -7090838833074031471                    0]


In [56]:
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 & arr2)

[ True False False False  True]
[False  True  True  True False]
[ True False False False  True]
[False  True  True  True False]
[False False False False False]
[ True  True  True  True  True]
[ 1 25  8  4 16]


In [57]:
arr1[arr1 > arr2]

array([85, 51])

In [58]:
# Vector product(dot product) - np.dot(arr1, arr2)
# No of elements in both the array shgould be same
print(arr1)
print()
print(arr2)

[85 31 26 21 51]

[11 89 76 38 24]


In [59]:
np.dot(arr1, arr2)

np.int64(7692)

### Understaing operations on 2D arrays

In [69]:
arr1 = np.random.randint(10, 30, 50).reshape(10, 5)
arr1

array([[28, 19, 17, 24, 17],
       [20, 28, 18, 24, 18],
       [20, 24, 17, 13, 24],
       [15, 13, 11, 11, 16],
       [29, 24, 15, 19, 23],
       [12, 21, 21, 10, 27],
       [20, 26, 22, 11, 27],
       [19, 23, 29, 28, 10],
       [22, 18, 23, 22, 24],
       [13, 21, 16, 27, 29]])

In [68]:
arr2 = np.random.randint(10, 70, 50).reshape(10, 5)
arr2

array([[59, 24, 17, 30, 55],
       [63, 35, 50, 59, 64],
       [53, 66, 26, 23, 27],
       [41, 37, 28, 66, 49],
       [18, 69, 21, 12, 25],
       [11, 16, 23, 52, 69],
       [58, 61, 42, 66, 53],
       [29, 52, 52, 61, 21],
       [51, 45, 33, 67, 63],
       [34, 38, 45, 33, 65]])

In [62]:
arr1+arr2

array([[49, 81, 63, 87, 83],
       [85, 83, 80, 88, 80],
       [43, 78, 64, 35, 68],
       [76, 54, 57, 38, 38],
       [76, 53, 65, 54, 72],
       [41, 29, 60, 48, 55],
       [55, 71, 53, 81, 41],
       [28, 45, 46, 75, 24],
       [63, 41, 62, 58, 38],
       [26, 24, 56, 60, 52]])

In [63]:
arr1 -= arr2       # arr1 = arr1-arr2
arr1

array([[ -9, -37, -17, -35, -31],
       [-39, -37, -58, -50, -58],
       [ -7, -26, -36,   5, -36],
       [-34, -14, -21,  12,   8],
       [-20, -25, -37,   4, -46],
       [  3,  -1,  -6, -10, -13],
       [-35, -45, -29, -41,  13],
       [  8,  -9, -20, -17,  -2],
       [ -7,  -7, -10, -34,   0],
       [  6,   0,  -8, -16,   0]])

In [64]:
arr1 <= arr2

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [70]:
# Unary operations on array - max, min, sum

print(np.max(arr1))

29


In [71]:
print(np.min(arr1))

10


In [72]:
print(np.sum(arr1))

1008


In [73]:
np.mean(arr1)

np.float64(20.16)

In [75]:
arr1

array([[28, 19, 17, 24, 17],
       [20, 28, 18, 24, 18],
       [20, 24, 17, 13, 24],
       [15, 13, 11, 11, 16],
       [29, 24, 15, 19, 23],
       [12, 21, 21, 10, 27],
       [20, 26, 22, 11, 27],
       [19, 23, 29, 28, 10],
       [22, 18, 23, 22, 24],
       [13, 21, 16, 27, 29]])

In [76]:
np.max(arr1, axis = 0)     # axis = 0 means find the max value for corresponding index in each row of this array

array([29, 28, 29, 28, 29])

In [77]:
np.max(arr1, axis = 1)

array([28, 28, 24, 16, 29, 27, 27, 29, 24, 29])

### Indexing and Slicing

In [78]:
arr1 = np.random.randint(10, 20, 10)
arr1

array([13, 11, 13, 19, 10, 13, 12, 17, 17, 19])

In [79]:
print(arr1[0])
print(arr1[-1])
print(arr1[3:4])

13
19
[19]


In [80]:
print(arr1[5:1:-1])

[13 10 19 13]


In [81]:
arr1 = np.random.randint(10, 20, 30).reshape(5, 6)
print(arr1)

[[15 19 11 15 11 15]
 [14 12 11 13 12 15]
 [19 13 19 13 15 16]
 [19 13 17 18 16 17]
 [11 13 15 16 16 10]]


In [83]:
print(arr1[1, 1])
print(arr1[1][1])

12
12


In [84]:
print(arr1[::, ::])

[[15 19 11 15 11 15]
 [14 12 11 13 12 15]
 [19 13 19 13 15 16]
 [19 13 17 18 16 17]
 [11 13 15 16 16 10]]


In [85]:
print(arr1[::])

[[15 19 11 15 11 15]
 [14 12 11 13 12 15]
 [19 13 19 13 15 16]
 [19 13 17 18 16 17]
 [11 13 15 16 16 10]]


In [86]:
print(arr1)

[[15 19 11 15 11 15]
 [14 12 11 13 12 15]
 [19 13 19 13 15 16]
 [19 13 17 18 16 17]
 [11 13 15 16 16 10]]


In [87]:
arr1[0]

array([15, 19, 11, 15, 11, 15])

In [90]:
arr1[::, 0]

array([15, 14, 19, 19, 11])

In [ ]:
arr1[0]

In [91]:
arr1

array([[15, 19, 11, 15, 11, 15],
       [14, 12, 11, 13, 12, 15],
       [19, 13, 19, 13, 15, 16],
       [19, 13, 17, 18, 16, 17],
       [11, 13, 15, 16, 16, 10]])

In [92]:
print(arr1[1:3])

[[14 12 11 13 12 15]
 [19 13 19 13 15 16]]


In [93]:
print(arr1[1:3, ::])

[[14 12 11 13 12 15]
 [19 13 19 13 15 16]]


In [94]:
arr1

array([[15, 19, 11, 15, 11, 15],
       [14, 12, 11, 13, 12, 15],
       [19, 13, 19, 13, 15, 16],
       [19, 13, 17, 18, 16, 17],
       [11, 13, 15, 16, 16, 10]])

In [95]:
print(arr1[::, 1:3])

[[19 11]
 [12 11]
 [13 19]
 [13 17]
 [13 15]]


In [96]:
print(arr1[1:3, 1:3])

[[12 11]
 [13 19]]


In [97]:
print(arr1[2:, 3:])

[[13 15 16]
 [18 16 17]
 [16 16 10]]


In [98]:
arr1

array([[15, 19, 11, 15, 11, 15],
       [14, 12, 11, 13, 12, 15],
       [19, 13, 19, 13, 15, 16],
       [19, 13, 17, 18, 16, 17],
       [11, 13, 15, 16, 16, 10]])

In [99]:
print(arr1[1:4:2, 1:4:2])

# [12,13],
# [13,18],

[[12 13]
 [13 18]]


In [100]:
res = arr1[1, 2], arr1[2, 2], arr1[1, 5], arr1[4, 5]
print(res, type(res))

(np.int64(11), np.int64(19), np.int64(15), np.int64(10)) <class 'tuple'>


In [101]:
row_ind = [1, 2, 1, 4]
col_ind = [2, 2, 5, 5]
arr1[row_ind, col_ind]

array([11, 19, 15, 10])

In [102]:
fruit = np.array([["Banana","Mango","Guava","Avacado"],
            ["Papaya","Jack fruit","Plum","Strawberry"],
            ["Apricot","Apple","Blue berry","Black berry"]])

fruit

array([['Banana', 'Mango', 'Guava', 'Avacado'],
       ['Papaya', 'Jack fruit', 'Plum', 'Strawberry'],
       ['Apricot', 'Apple', 'Blue berry', 'Black berry']], dtype='<U11')

In [103]:
# (0, 1), (1, 1), (1, 3), (2, 2) -> 'Potato'

row_ind = [0,1,1,2]
col_ind = [1, 1, 3, 2]
fruit[row_ind, col_ind] = 'Potato'
fruit

array([['Banana', 'Potato', 'Guava', 'Avacado'],
       ['Papaya', 'Potato', 'Plum', 'Potato'],
       ['Apricot', 'Apple', 'Potato', 'Black berry']], dtype='<U11')